// Kannada names of Karnataka's taluks, keyed by the Agriculture Census name the data uses ("K.R. PET").
// From OpenStreetMap (name:kn of every Karnataka taluk, ODbL), matched to the 175 Census 2011 taluks by place:
// the OpenStreetMap taluk whose centre lies in the census taluk and whose name is closest. Checked by hand;
// seven are corrected (OpenStreetMap wrong for Devanahalli and Bhatkal, a neighbouring new taluk matched for
// Hospet, H.D. Kote and K.R. Nagara, Supa renamed Joida, Gulbarga written Kalaburagi as the district is).
// Used by talukName() in translations.ts.

export const TALUK_NAMES_KN: Record<string, string> = {
  'AFZALPUR + ALAND': 'ಅಫ್ಜಲಪುರ + ಆಳಂದ',
  'ALUR': 'ಆಲೂರು',
  'ANEKAL': 'ಆನೇಕಲ್',
  'ANKOLA': 'ಅಂಕೋಲ',
  'ARASIKERE': 'ಅರಸೀಕೆರೆ',
  'ARKALGUD': 'ಅರಕಲಗೂಡು',
  'ATHANI': 'ಅಥಣಿ',
  'AURAD': 'ಔರಾದ್',
  'BADAMI': 'ಬಾದಾಮಿ',
  'BAGALKOTE': 'ಬಾಗಲಕೋಟೆ',
  'BAGEPALLI': 'ಬಾಗೇಪಲ್ಲಿ',
  'BAILHONGAL': 'ಬೈಲಹೊಂಗಲ',
  'BANGALORE EAST': 'ಬೆಂಗಳೂರು ಪೂರ್ವ',
  'BANGALORE NORTH': 'ಬೆಂಗಳೂರು ಉತ್ತರ',
  'BANGALORE SOUTH': 'ಬೆಂಗಳೂರು ದಕ್ಷಿಣ',
  'BANGARPET': 'ಬಂಗಾರಪೇಟೆ',
  'BANTWAL': 'ಬಂಟ್ವಾಳ',
  'BASAVAKALYAN': 'ಬಸವಕಲ್ಯಾಣ',
  'BASAVANA BAGEVADI': 'ಬಸವನ ಬಾಗೇವಾಡಿ',
  'BELGAUM': 'ಬೆಳಗಾವಿ',
  'BELLARY': 'ಬಳ್ಳಾರಿ',
  'BELTANGADY': 'ಬೆಳ್ತಂಗಡಿ',
  'BELUR': 'ಬೇಲೂರು',
  'BHADRAVATHI': 'ಭದ್ರಾವತಿ',
  'BHALKI': 'ಭಾಲ್ಕಿ',
  'BHATKAL': 'ಭಟ್ಕಳ',
  'BIDAR': 'ಬೀದರ್',
  'BIJAPUR': 'ವಿಜಯಪುರ',
  'BILGI': 'ಬೀಳಗಿ',
  'BYADAGI': 'ಬ್ಯಾಡಗಿ',
  'CHALLAKERE': 'ಚಳ್ಳಕೆರೆ',
  'CHAMARAJANAGAR': 'ಚಾಮರಾಜನಗರ',
  'CHANNAGIRI': 'ಚನ್ನಗಿರಿ',
  'CHANNAPATNA': 'ಚನ್ನಪಟ್ಟಣ',
  'CHANNARAYAPATNA': 'ಚನ್ನರಾಯಪಟ್ಟಣ',
  'CHICHBALLAPURA': 'ಚಿಕ್ಕಬಳ್ಳಾಪುರ',
  'CHIKKAMAGALUR': 'ಚಿಕ್ಕಮಗಳೂರು',
  'CHIKKANAYAKANAHALLI': 'ಚಿಕ್ಕನಾಯಕನಹಳ್ಳಿ',
  'CHIKKODI': 'ಚಿಕ್ಕೋಡಿ',
  'CHINCHOLI': 'ಚಿಂಚೋಳಿ',
  'CHINTAMANI': 'ಚಿಂತಾಮಣಿ',
  'CHITAPUR': 'ಚಿತಾಪುರ',
  'CHITRADURGA': 'ಚಿತ್ರದುರ್ಗ',
  'DAVANAGERE': 'ದಾವಣಗೆರೆ',
  'DEVANAHALLI': 'ದೇವನಹಳ್ಳಿ',
  'DEVDURGA': 'ದೇವದುರ್ಗ',
  'DHARWAD': 'ಧಾರವಾಡ',
  'DODDABALLAPUR': 'ದೊಡ್ಡಬಳ್ಳಾಪುರ',
  'GADAG': 'ಗದಗ',
  'GANGAVATHI': 'ಗಂಗಾವತಿ',
  'GOKAK': 'ಗೋಕಾಕ',
  'GOURIBADANUR': 'ಗೌರಿಬಿದನೂರು',
  'GUBBI': 'ಗುಬ್ಬಿ',
  'GUDIBANDA': 'ಗುಡಿಬಂಡೆ',
  'GUDLUPET': 'ಗುಂಡ್ಲುಪೇಟೆ',
  'GULBARGA': 'ಕಲಬುರಗಿ',
  'H.D. KOTE': 'ಹೆಗ್ಗಡದೇವನಕೋಟೆ',
  'HADAGALI': 'ಹೂವಿನಹಡಗಲಿ',
  'HAGARIBOMMANAHALLI': 'ಹಗರಿಬೊಮ್ಮನಹಳ್ಳಿ',
  'HALIYAL': 'ಹಳಿಯಾಳ',
  'HANAGAL': 'ಹಾನಗಲ್',
  'HARAPANAHALLI': 'ಹರಪನಹಳ್ಳಿ',
  'HARIHARA': 'ಹರಿಹರ',
  'HASSAN': 'ಹಾಸನ',
  'HAVERI': 'ಹಾವೇರಿ',
  'HIREKERUR': 'ಹಿರೇಕೆರೂರು',
  'HIRIYUR': 'ಹಿರಿಯೂರು',
  'HOLALKERE': 'ಹೊಳಲ್ಕೆರೆ',
  'HOLENARASIPURA': 'ಹೊಳೆ ನರಸೀಪುರ',
  'HONNALI': 'ಹೊನ್ನಾಳಿ',
  'HONNAVAR': 'ಹೊನ್ನಾವರ',
  'HOSADURGA': 'ಹೊಸದುರ್ಗ',
  'HOSAKOTE': 'ಹೊಸಕೋಟೆ',
  'HOSANAGARA': 'ಹೊಸನಗರ',
  'HOSPET': 'ಹೊಸಪೇಟೆ',
  'HUBLI': 'ಹುಬ್ಬಳ್ಳಿ',
  'HUKKERI': 'ಹುಕ್ಕೇರಿ',
  'HUMNABAD': 'ಹುಮನಾಬಾದ್',
  'HUNGUNDA': 'ಹುನಗುಂದ',
  'HUNSUR': 'ಹುಣಸೂರು',
  'INDI': 'ಇಂಡಿ',
  'JAGALUR': 'ಜಗಳೂರು',
  'JAMKHANDI': 'ಜಮಖಂಡಿ',
  'JEWARGI': 'ಜೇವರ್ಗಿ',
  'K.R. NAGARA': 'ಕೃಷ್ಣರಾಜನಗರ',
  'K.R. PET': 'ಕೃಷ್ಣರಾಜಪೇಟೆ',
  'KADUR': 'ಕಡೂರು',
  'KALGHATGI': 'ಕಲಘಟಗಿ',
  'KANKAPUR': 'ಕನಕಪುರ',
  'KARKALA': 'ಕಾರ್ಕಳ',
  'KARWAR': 'ಕಾರವಾರ',
  'KHANAPUR': 'ಖಾನಾಪುರ',
  'KOLAR': 'ಕೋಲಾರ',
  'KOLLEGAL': 'ಕೊಳ್ಳೇಗಾಲ',
  'KOPPA': 'ಕೊಪ್ಪ',
  'KOPPAL': 'ಕೊಪ್ಪಳ',
  'KORATAGERE': 'ಕೊರಟಗೆರೆ',
  'KUDALGI': 'ಕೂಡ್ಲಿಗಿ',
  'KUMTA': 'ಕುಮಟಾ',
  'KUNDAPURA': 'ಕುಂದಾಪುರ',
  'KUNDGOL': 'ಕುಂದಗೋಳ',
  'KUNIGAL': 'ಕುಣಿಗಲ್',
  'KUSHTAGI': 'ಕುಷ್ಟಗಿ',
  'LINGSUGUR': 'ಲಿಂಗಸುಗೂರು',
  'MADDUR': 'ಮದ್ದೂರು',
  'MADHUGIRI': 'ಮಧುಗಿರಿ',
  'MADIKERI': 'ಮಡಿಕೇರಿ',
  'MAGADI': 'ಮಾಗಡಿ',
  'MALAVALLI': 'ಮಳವಳ್ಳಿ',
  'MALUR': 'ಮಾಲೂರು',
  'MANDYA': 'ಮಂಡ್ಯ',
  'MANGALORE': 'ಮಂಗಳೂರು',
  'MANVI': 'ಮಾನ್ವಿ',
  'MOLKALMUR': 'ಮೊಳಕಾಲ್ಮೂರು',
  'MUDDEBIHAL': 'ಮುದ್ದೇಬಿಹಾಳ',
  'MUDHOL': 'ಮುಧೋಳ',
  'MUDIGERE': 'ಮೂಡಿಗೆರೆ',
  'MULBAGAL': 'ಮುಳುಬಾಗಿಲು',
  'MUNDARGI': 'ಮುಂಡರಗಿ',
  'MUNDGOD': 'ಮುಂಡಗೋಡ',
  'MYSORE': 'ಮೈಸೂರು',
  'N.R. PURA': 'ನರಸಿಂಹರಾಜಪುರ',
  'NAGAMANGALA': 'ನಾಗಮಂಗಲ',
  'NANJANGUD': 'ನಂಜನಗೂಡು',
  'NARAGUND': 'ನರಗುಂದ',
  'NAVALGUND': 'ನವಲಗುಂದ',
  'NELAMANGALA': 'ನೆಲಮಂಗಲ',
  'PANDAVAPURA': 'ಪಾಂಡವಪುರ',
  'PAVAGADA': 'ಪಾವಗಡ',
  'PERIYAPATNA': 'ಪಿರಿಯಾಪಟ್ಟಣ',
  'PUTTUR': 'ಪುತ್ತೂರು',
  'RAIBAG': 'ರಾಯಬಾಗ',
  'RAICHUR': 'ರಾಯಚೂರು',
  'RAMANAGAR': 'ರಾಮನಗರ',
  'RAMDURGA': 'ರಾಮದುರ್ಗ',
  'RANEBENNUR': 'ರಾಣೆಬೆನ್ನೂರು',
  'RON': 'ರೋಣ',
  'SAGARA': 'ಸಾಗರ',
  'SAKALESHPUR': 'ಸಕಲೇಶಪುರ',
  'SANDUR': 'ಸಂಡೂರು',
  'SAVANUR': 'ಸವಣೂರ',
  'SEDAM': 'ಸೇಡಂ',
  'SHAHAPUR': 'ಶಹಾಪುರ',
  'SHIGGAON': 'ಶಿಗ್ಗಾವಿ',
  'SHIKARIPURA': 'ಶಿಕಾರಿಪುರ',
  'SHIMOGA': 'ಶಿವಮೊಗ್ಗ',
  'SHIRAHATTI': 'ಶಿರಹಟ್ಟಿ',
  'SHORAPUR': 'ಸುರಪುರ',
  'SIDDAPUR': 'ಸಿದ್ದಾಪುರ',
  'SIDLAGHATTA': 'ಶಿಡ್ಲಘಟ್ಟ',
  'SINDGI': 'ಸಿಂದಗಿ',
  'SINDHANUR': 'ಸಿಂಧನೂರು',
  'SIRA': 'ಸಿರಾ',
  'SIRSI': 'ಶಿರಸಿ',
  'SIRUGUPPA': 'ಶಿರುಗುಪ್ಪ',
  'SOMWARPET': 'ಸೋಮವಾರಪೇಟೆ',
  'SORABA': 'ಸೊರಬ',
  'SOUNDATTI': 'ಸವದತ್ತಿ',
  'SRINGERI': 'ಶೃಂಗೇರಿ',
  'SRINIVASAPUR': 'ಶ್ರೀನಿವಾಸಪುರ',
  'SRIRANGAPATNA': 'ಶ್ರೀರಂಗಪಟ್ಟಣ',
  'SULYA': 'ಸುಳ್ಯ',
  'SUPA': 'ಸೂಪಾ (ಜೋಯಿಡಾ)',
  'T. NARASIPURA': 'ತಿರುಮಕೂಡಲು ನರಸೀಪುರ',
  'TARIKERE': 'ತರಿಕೆರೆ',
  'THIRTHAHALLI': 'ತೀರ್ಥಹಳ್ಳಿ',
  'TIPTUR': 'ತಿಪಟೂರು',
  'TUMKUR': 'ತುಮಕೂರು',
  'TURUVEKERE': 'ತುರುವೇಕೆರೆ',
  'UDUPI': 'ಉಡುಪಿ',
  'VIRAJPET': 'ವಿರಾಜಪೇಟೆ',
  'YADGIR': 'ಯಾದಗಿರಿ',
  'YELANDUR': 'ಯಳಂದೂರು',
  'YELBURGA': 'ಯಲಬುರ್ಗಾ',
  'YELLAPUR': 'ಯಲ್ಲಾಪುರ',
};
